### PR TITLE
readme: simplified part about downloading selenium

### PR DESCRIPTION
**Pull request by joozek78**

### CODE REVIEW

**Comment by joozek78** [comment]
Did anyone have problem with putting drivers beside selenium jar?

**Comment by miyconst** [comment]
Yes, I did, and I appreciated the more detailed readme.

**Comment by joozek78** [comment]
@miyconst What exact problems did you have? I'm running it without issues

**Comment by warpech** [comment]
Very good, thank you!

**Comment by warpech** [comment]
I felt inspired to do a even simpler version: https://github.com/StarcounterSamples/KitchenSink/pull/45

**Pull request merged**
