### PR TITLE
Show the processing status for self-disabling/enabling button a little longer

### PR DESCRIPTION
**Pull request by un-tone**
For https://github.com/StarcounterSamples/KitchenSink/issues/87.

### CODE REVIEW

**Comment by un-tone** [comment]
@warpech, I agree

**Comment by un-tone** [comment]
Changes are ready. please check

**Comment by warpech** [comment]
Solving problems through removing code - great!

**Comment by warpech** [comment]
One more thing - @joozek78 brought to my attention that `Thread.Sleep` usually is a code smell. Maybe this could be solved with `await Task.Delay(500)`? It will probably require [`Scheduling.ScheduleTask`](https://docs.starcounter.io/guides/transactions/running-background-jobs/)

This is a sample app, it should show good practices.

@un-tone, @joozek78 WDYT?

**Comment by warpech** [comment]
@KmaTTi89 I think that we need to decide to one target branch. Would you like this to be merged to `develop` or `new_tests_project`?

If `new_tests_project` then @un-tone please change the target branch of the PR.

**Comment by warpech** [comment]
I think that the correct flow is to merge to `develop` and then @KmaTTi89 solves conflicts in his branch since he owns that branch.

**Comment by KmaTTi89** [comment]
Currently I am try to resolve confilcts on my branch because of these changes so please merge to dev then merge my branch with dev. Lets see what will happen

**Comment by warpech** [comment]
@KmaTTi89 you should merge `develop` to your feature branch, since you own the feature branch.

**Comment by KmaTTi89** [comment]
@warpech I don't understand. How to merge develop with my branch. My branch is going to replace all code currently in develop. These changes are for tests so should be places in my branch then my branch should be merge with develop

**Comment by joozek78** [comment]
Re: Thread.Sleep
I have to clarify - I just was just suspicious when I saw that somebody is sleeping in the code ;p
It seems to be justified here - we're simulating work that takes time. Changing it to `Task.Delay` wouldn't actually change anything here. It's just fine

**Comment by warpech** [comment]
If `new_tests_project` branch has conflicts with `develop` (it currently has), it cannot be merged to `develop` without first merging `develop` to it in order to solve conflicts.

> To avoid conflicts during finishing feature branch, ensure that all changes from develop are merged to the feature branch.

Thats a quote from http://mkuthan.github.io/blog/2013/07/21/gitflow-step-by-step/. We are not using strict GitFlow, but something very similar to it. I recommend reading the above guide.

**Comment by un-tone** [comment]
I agree with @joozek78 , calling `Thread.Sleep` here is just for simulating work. I suppose using of the complicated approach will be confusing to others.

**Comment by warpech** [comment]
Ok, then it is fine by me!

@un-tone maybe you can propose strategy to close this PR. Since @KmaTTi89 has merged from one feature branch to another feature branch, it should be enough to change the PR target from `develop` to `new_tests_project` to merge without conflicts.

**Comment by un-tone** [comment]
@warpech, in a standard case I would target these PRs to `develop`. But since these issues are related directly to the test covering issues I assume it more correct to target the PRs to the `new_tests_project` branch.

**Comment by un-tone** [comment]
Please confirm re-targeting of the PR.

**Comment by warpech** [comment]
I confirm.

**Comment by un-tone** [comment]
Closing. Changes from the `feature/Self-Enabling-Disabling-Button-State` branch is already merged with `new_tests_project` manually.

**Pull request closed without merging**
