### PR TITLE
Parallelizable test

### PR DESCRIPTION
**Pull request by KmaTTi89**
- update tests to run parallel
- update nunit
- update webdriver
- disable screenshot maker due firefox bug

### CODE REVIEW

**Comment by warpech** [comment]
@miyconst Could you please review? Does it work like you wanted https://github.com/StarcounterSamples/KitchenSink/pull/62 to work?

**Comment by miyconst** [comment]
@warpech you never stop working, even at the airport :). Will check it as soon as I get home.

**Comment by miyconst** [comment]
Yes. This is something I wanted. @KmaTTi89 could you please share numbers? How much time do we save by executing it in parallel? Unfortunately I don't have Selenium environment at my home PC to check.

**Comment by warpech** [comment]
@KmaTTi89 wrote me on Slack that it decreased testing time from 5 minutes to 50 seconds.

**Comment by warpech** [comment]
On my machine the running time is decreased from 6m15.711s to 3m52.919s.

Measured using `time cmd //c "test.bat"` in Git Bash.

**Comment by KmaTTi89** [comment]
Old build on TeamCity: about 5 minutes
New build on TeamCity with Parallel tests: about 1 and a half minute

**Pull request merged**
