### PR TITLE
Update to NUnit 3 and Parallelizable tests

### PR DESCRIPTION
**Pull request by miyconst**

### CODE REVIEW

**Comment by warpech** [comment]
I am afraid that the tests might encounter this problem: https://github.com/Starcounter/Starcounter/issues/3798

Let's see how it works. I have scheduled a build to test that: https://scbuildserver/viewQueued.html?itemId=10356

**Comment by miyconst** [comment]
>I am afraid that the tests might encounter this problem: Starcounter/Starcounter#3798

That is rather a serious issue, and it could be a push to fix it.

**Comment by warpech** [comment]
Locally, I have some random failures. See the below screenshot.

On the build server, there are some `nuget` problems. Any idea why? Doesn't msbuild restore nuget packages?

```
[15:28:31][Step 1/1] kitchensink_selenium_test-bat (30s)
[15:28:31][kitchensink_selenium_test-bat] -- Running test "kitchensink_selenium_test.bat" (max duration: 600 s) at "C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink\kitchensink_selenium_test.bat"
[15:28:31][kitchensink_selenium_test-bat] -- Running process "staradmin kill all"
[15:28:31][kitchensink_selenium_test-bat] 15:28:31.8555007: process 'scservice' successfully killed!
[15:28:31][kitchensink_selenium_test-bat] 15:28:31.8657146: process 'scnetworkgateway' successfully killed!
[15:28:31][kitchensink_selenium_test-bat] 15:28:31.8799610: process 'scadminserver' successfully killed!
[15:28:32][kitchensink_selenium_test-bat] 15:28:32.0644786: process 'sccode' successfully killed!
[15:28:32][kitchensink_selenium_test-bat] 15:28:32.0675348: process 'scdata' successfully killed!
[15:28:32][kitchensink_selenium_test-bat] 15:28:32.0695717: process 'scdblog' successfully killed!
[15:28:32][kitchensink_selenium_test-bat] 15:28:32.0726248: process 'scsqlparser' successfully killed!
[15:28:32][kitchensink_selenium_test-bat] 15:28:32.0767125: process 'sctrayicon' successfully killed!
[15:28:32][kitchensink_selenium_test-bat] -- Running process "C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink\kitchensink_selenium_test.bat "
[15:28:32][kitchensink_selenium_test-bat] 
[15:28:32][kitchensink_selenium_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink>IF "Release" == "" set Configuration=Debug 
[15:28:32][kitchensink_selenium_test-bat] 
[15:28:32][kitchensink_selenium_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink>star -d=kitchensink --resourcedir="C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink\src\KitchenSink\wwwroot" "C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink\bin/Release/KitchenSink.exe" 
[15:29:02][kitchensink_selenium_test-bat] 
[15:29:02][kitchensink_selenium_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink>IF ERRORLEVEL 1 EXIT /b 1 
[15:29:02][kitchensink_selenium_test-bat] 
[15:29:02][kitchensink_selenium_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink>packages\NUnit.ConsoleRunner.3.2.0\tools\nunit3-console.exe test\KitchenSink.Tests\KitchenSink.Tests.csproj /config:Release 
[15:29:02][kitchensink_selenium_test-bat] The system cannot find the path specified.
[15:29:02][kitchensink_selenium_test-bat] 
[15:29:02][kitchensink_selenium_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-483\kitchensink>IF ERRORLEVEL 1 EXIT /b 1 
[15:29:02][kitchensink_selenium_test-bat] The test has failed. See build log for details.
```

**Comment by miyconst** [comment]
Are all of those failures Edge related? If so, then I might rework the tests to execute one by one inside a browser, but in all browsers at the same time.

Anyway, we should get use of the hardware we have. It can be executed in parallel, if designed properly.

**Comment by warpech** [comment]
Actually I have switched my local KitchenSink to use the prototype [`PuppetJsProvider`](https://github.com/StarcounterSamples/HelloWorld/commit/49a8e95323b4f271de71de8647f44d3ff278444f) (which solves https://github.com/Starcounter/Starcounter/issues/3798). Sadly, the KitchenSink nunit3 tests still don't work.

Most of the failed tests are Edge, though there is also one Chrome and one Firefox.

Did all tests pass for you?

**Comment by warpech** [comment]
I have pushed my PuppetJsProvider experiment if you'd like to take a look: https://github.com/StarcounterSamples/KitchenSink/tree/nunit3-puppetjsprovider

**Comment by miyconst** [comment]
Yes, all the tests passed for me multiple times. It can be related to machine's power.

Can you execute the failed tests one by one and see if any fails? Most likely not, but I want to make sure.

I will check how to remove the parallel execution inside a browser.

**Comment by warpech** [comment]
I will try again today.

This needs fixing anyway: Trying to run the tests from `test.bat` gives me an error (see below). Could you please investigate?

2016-09-14 14_35_40-command prompt

**Comment by miyconst** [comment]
I will try to look at it, but probably not any time soon.

**Comment by warpech** [comment]
Other than that there is one test that fails for me always: `CheckboxPage_CheckboxUncheckedAndCheckedAgain`

What's your setup? Mine:
- Selenium and drivers from here https://www.dropbox.com/sh/30flfnnq6feu77v/AABAMDMl8NQV4__oyLi9RWxOa?dl=0
- Windows 10 AE
- Starcounter 2.2.1.3154
- Edge 38.14393.0.0 / EdgeHTML 14.14393
- Firefox 48.0.2
- Chrome 53.0.2785.113 m (64-bit)

Assigning it on you for fixing of `test.bat`.

**Comment by warpech** [comment]
Closing this PR no longer mergable. Thank you @miyconst for your investigation anyway. @KmaTTi89 will continue in https://github.com/StarcounterSamples/KitchenSink/issues/95

**Pull request closed without merging**
